name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your default branch name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action-gh-pages@v1 # A versatile action that works well
        # If using Vite, it auto-detects. For others, you might need configuration.
        # with:
        #   path: dist # The folder where your build output is located

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
